### ISSUE TITLE
GaussSum3.0.2 in Debian10(buster)

### ISSUE THREAD

**Issue by grigarcia** [gausssum/gausssum#18]
I installed GaussSum on my laptop with Debian 10, but I am having problems to make any type of graph from Gaussian 16 output file. I only get error messages (as seen in the photos below). Any help will be very welcome. 

![image](https://user-images.githubusercontent.com/92613676/147312267-c7820169-99cb-4531-a3f8-c9e2f82a450f.png)

![image](https://user-images.githubusercontent.com/92613676/147312150-a8398c39-94c3-4bb1-9812-b30e4a98ad9d.png)

![image](https://user-images.githubusercontent.com/92613676/147312287-8df20b4b-ff47-4f30-9fa0-b646df09bb3b.png)

**Comment by mlunik** [comment]
The same is happening in ubuntu 20.04 after upgrading from 18.04. The error is related to matplotlib. See https://stackoverflow.com/questions/35829961/using-matplotlib-with-tkinter-tkagg

The solution is to edit /usr/lib/python3/dist-packages/gausssum/plot.py:
lines 22 and 43: change "NavigationToolbar2TkAgg" to "NavigationToolbar2Tk"
Iine 40: change "canvas.show()" to "canvas.draw()"
line 47: add  "canvas.draw()" - this solves the size problem of the graph

Addidionally for Electronic transitions one has to change "cm-1" to "wavenumber" in /usr/lib/python3/dist-packages/gausssum/electrontrans.py as cclib is looking for wavenumbers instead of cm-1. 

This would be lines 322, 340, 341, 352, 354, 363, 366, 391, 392, 393, 419, 435, 437.

**Comment by baoilleach** [comment]
I've made those changes @mlunik. I just happened to need to use GaussSum today after a break of oh 15 years, and so I found these comments very useful.

To install on Linux, the following is probably the easiest approach now:
```
conda create -n gausssum -c conda-forge matplotlib cclib gnuplot
conda activate gausssum
git clone https://github.com/gausssum/gausssum.git
cd gausssum
python src/GaussSum.py
```
Actually, is GnuPlot still required? I don't remember. Needless to say, if anyone wants to help out maintaining GaussSum, they are very welcome. For example, making a new release, updating and moving the docs over to GitHub, etc.

**Comment by rafaelpap** [comment]
I believe there is something wrong with the last changes. 
In electrontrans.py  the argument for convertor should be "wavenumber" instead of "wavenumbers".
Also line 43 in plot.py shoul use NavigationToolbar2Tk instead of NavigationToolbar2TkAgg
