### ISSUE TITLE
Small error in activity_to_intensity Raman calculation

### ISSUE THREAD

**Issue by gadass** [gausssum/gausssum#7]
Dear all,

I would like to report what I think it is a small error in the routine of GaussSum. In the vibfreq.py file, when the exponential term is calculated, the following is written correctly?

"exponential = -6.626068e-34 * 299792458 * frequency / (1.3806503e-23 * temperature)"

I think that this light velocity value is in units of cm/sec. If so, the correct value should be 299792458e2. Therefore:

"exponential = -6.626068e-34 * 299792458**e2** * frequency / (1.3806503e-23 * temperature)"

This small modification allows a better description of the Raman intensities at low-frequency, at least in my calculations.

Does this make sense?

Best,

José Gadelha, PhD
Department of Materials Science 
UFMA, Imperatriz

**Comment by zjagoo** [comment]
Hello gadass,
I believe that the formula is correct because the frequencies given in the log file and subsequently gausssum is in cm-1 (wavenumber). To validate this, you can issue 'print(frequency)' on line 29 in vibfreq.py file and watch the console or look for the raman modes in your log file. Because the frequencies are given in cm-1, instead of m-1, the speed of light needs to be divided by 100.
Regards.
